// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbbjuworsblonwvfywsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiYmp1d29yc2Jsb253dmZ5d3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjE2MjMsImV4cCI6MjA2NTQ5NzYyM30.6CSkPnFHRwMgoTCPHOX68VuZAEBR1L1RBoA4S0s9Z6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);